SwapBooksApp/Controllers/AutorskoDjeloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SwapBooksApp.Data;
using SwapBooksApp.Models;

namespace SwapBooksApp.Controllers
{
    [Authorize(Roles = "Administrator, SuperKorisnik")]
    public class AutorskoDjeloController : Controller
    {
        private readonly ApplicationDbContext _context;
        private  UserManager<Korisnik> userManager;

        public AutorskoDjeloController(ApplicationDbContext context, UserManager<Korisnik> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        // GET: AutorskoDjelo
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.AutorskoDjelo.Include(a => a.Korisnik);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: AutorskoDjelo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autorskoDjelo = await _context.AutorskoDjelo
                .Include(a => a.Korisnik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (autorskoDjelo == null)
            {
                return NotFound();
            }

            return View(autorskoDjelo);
        }

        // GET: AutorskoDjelo/Create
        public IActionResult Create()
        {
            ViewData["korisnikId"] = new SelectList(_context.Set<Korisnik>(), "Id", "Id");
            return View();
        }

        // POST: AutorskoDjelo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,Ocjena,korisnikId,Cijena,Autor")] AutorskoDjelo autorskoDjelo)
        {
            if (ModelState.IsValid)
            {

                Korisnik korisnik = (await userManager.GetUserAsync(HttpContext.User));
                autorskoDjelo.korisnikId = korisnik.Id;
                // knjiga.Korisnik = korisnik;
                

                _context.Add(autorskoDjelo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["korisnikId"] = new SelectList(_context.Set<Korisnik>(), "Id", "Id", autorskoDjelo.korisnikId);
            return View(autorskoDjelo);
        }

        // GET: AutorskoDjelo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autorskoDjelo = await _context.AutorskoDjelo.FindAsync(id);
            if (autorskoDjelo == null)
            {
                return NotFound();
            }
            ViewData["korisnikId"] = new SelectList(_context.Set<Korisnik>(), "Id", "Id", autorskoDjelo.korisnikId);
            return View(autorskoDjelo);
        }

        // POST: AutorskoDjelo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,Ocjena,korisnikId,Cijena,Autor")] AutorskoDjelo autorskoDjelo)
        {
            if (id != autorskoDjelo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(autorskoDjelo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutorskoDjeloExists(autorskoDjelo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["korisnikId"] = new SelectList(_context.Set<Korisnik>(), "Id", "Id", autorskoDjelo.korisnikId);
            return View(autorskoDjelo);
        }

        // GET: AutorskoDjelo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autorskoDjelo = await _context.AutorskoDjelo
                .Include(a => a.Korisnik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (autorskoDjelo == null)
            {
                return NotFound();
            }

            return View(autorskoDjelo);
        }

        // POST: AutorskoDjelo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var autorskoDjelo = await _context.AutorskoDjelo.FindAsync(id);
            _context.AutorskoDjelo.Remove(autorskoDjelo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AutorskoDjeloExists(int id)
        {
            return _context.AutorskoDjelo.Any(e => e.Id == id);
        }
        public async Task<IActionResult> Biblioteka()

        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var knjige = _context.AutorskoDjelo.
                        Where(k => k.korisnikId.Equals(userId));
            return View(await knjige.ToListAsync());

        }
    }
}

SwapBooksApp/Controllers/KnjigaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SwapBooksApp.Data;
using SwapBooksApp.Models;

namespace SwapBooksApp.Controllers
{
    public class KnjigaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public KnjigaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Knjiga
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Knjiga.Include(k => k.Korisnik);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Knjiga/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knjiga = await _context.Knjiga
                .Include(k => k.Korisnik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (knjiga == null)
            {
                return NotFound();
            }

            return View(knjiga);
        }

        // GET: Knjiga/Create
        public IActionResult Create()
        {
            ViewData["KorisnikId"] = new SelectList(_context.Set<Korisnik>(), "Id", "Id");
            return View();
        }

        // POST: Knjiga/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,KorisnikId,Zauzeta,Slika")] Knjiga knjiga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(knjiga);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["KorisnikId"] = new SelectList(_context.Set<Korisnik>(), "Id", "Id", knjiga.KorisnikId);
            return View(knjiga);
        }

        // GET: Knjiga/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knjiga = await _context.Knjiga.FindAsync(id);
            if (knjiga == null)
            {
                return NotFound();
            }
            ViewData["KorisnikId"] = new SelectList(_context.Set<Korisnik>(), "Id", "Id", knjiga.KorisnikId);
            return View(knjiga);
        }

        // POST: Knjiga/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,KorisnikId,Zauzeta,Slika")] Knjiga knjiga)
        {
            if (id != knjiga.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(knjiga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KnjigaExists(knjiga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KorisnikId"] = new SelectList(_context.Set<Korisnik>(), "Id", "Id", knjiga.KorisnikId);
            return View(knjiga);
        }

        // GET: Knjiga/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var knjiga = await _context.Knjiga
                .Include(k => k.Korisnik)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (knjiga == null)
            {
                return NotFound();
            }

            return View(knjiga);
        }

        // POST: Knjiga/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var knjiga = await _context.Knjiga.FindAsync(id);
            _context.Knjiga.Remove(knjiga);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KnjigaExists(int id)
        {
            return _context.Knjiga.Any(e => e.Id == id);
        }
    }
}

SwapBooksApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SwapBooksApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SwapBooksApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Knjiga" asp-action="Index">Sve knjige</a>
                        </li>
                        @if (User.IsInRole("ObicniKorisnik") || User.IsInRole("SuperKorisnik"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Knjiga" asp-action="Biblioteka">Biblioteka</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Knjiga" asp-action="Create">Dodaj Knjigu</a>
                            </li>
                        }
                        @if (User.IsInRole("SuperKorisnik"))
                        {


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AutorskoDjelo" asp-action="Create">Dodaj djelo</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AutorskoDjelo" asp-action="Biblioteka">Moja djela</a>
                            </li>

                        }
                         @if (User.IsInRole("Administrator"))
                        {
                               <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AutorskoDjelo" asp-action="Index">Sva autorska djela</a>
                            </li>
                        }

                         
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SwapBooksApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>